changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
      - wontfix
    authors:
      - dependabot
  categories:
    - title: New features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Home Assistant integration
      labels:
        - integration
        - home-assistant
    - title: Installer and release
      labels:
        - installer
        - github-actions
        - release
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
